In [1]:
import pandas as pd

In [2]:
import numpy as np
arr = np.array([1,2,3,4])
d1 = pd.Series(arr) 
d1

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [6]:
## Using dictionary 
d = {'a':1,'b':2,'c':3,'d':4}

In [7]:
b = pd.Series(d)
b

a    1
b    2
c    3
d    4
dtype: int64

## DataFrame

In [8]:
data = [['abc',1],['def',2],['ghi',3],['hij'],['klm',5]]

In [9]:
a = pd.DataFrame(data)
a

     0    1
0  abc  1.0
1  def  2.0
2  ghi  3.0
3  hij  NaN
4  klm  5.0

In [10]:
d=pd.DataFrame(data,columns=['A','B'],index=['A','B','C','D','E']) ## Changing the column names and index names
d

     A    B
A  abc  1.0
B  def  2.0
C  ghi  3.0
D  hij  NaN
E  klm  5.0

In [11]:
## DataFrame from dictionary
data = {'name':['a','b','c','d','e','f'],'age':[45,12,48,25,12,56]}
data

{'name': ['a', 'b', 'c', 'd', 'e', 'f'], 'age': [45, 12, 48, 25, 12, 56]}

In [12]:
d = pd.DataFrame(data)
d

  name  age
0    a   45
1    b   12
2    c   48
3    d   25
4    e   12
5    f   56

In [13]:
d.columns=['Candidate','Age_in_years']
d

  Candidate  Age_in_years
0         a            45
1         b            12
2         c            48
3         d            25
4         e            12
5         f            56

In [ ]:
d.rename({'Age_in_years':'Age'},axis=1,inplace=True) ## Axis = 1 means column and axis = 0 means row 
d

  Candidate  Age
0         a   45
1         b   12
2         c   48
3         d   25
4         e   12
5         f   56

In [15]:
import pandas as pd
import numpy as np

In [2]:
## Reading the data from github
import pandas as pd
data = pd.read_csv("C:\\Users\\HP\\OneDrive\\Documents\\DataMites\\Libraries\\titanic.csv")
data

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500

In [18]:
data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500

In [19]:
data.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.00
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.00
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.45
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.00
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.75

In [20]:
data.head(2)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833

In [21]:
type(data)

pandas.core.frame.DataFrame

In [22]:
data.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Fare      891 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [24]:
data["Pclass"].unique()

array([3, 1, 2])

In [25]:
data.shape # Shape is an attribute of the dataframe

(891, 8)

In [26]:
data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [27]:
data.describe() # Describe is a method of the dataframe

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
data.describe(include='O') # Describe is a method of the dataframe . O means object data type. It will give the summary of the categorical columns.

                           Name   Sex
count                       891   891
unique                      891     2
top     Braund, Mr. Owen Harris  male
freq                          1   577

In [ ]:
## Loc means location. It is used to get the rows and columns with particular condition. 

## iloc means index location. It is used to get the rows and columns with particular condition.

In [30]:
data.loc[data['Age']==80] # loc is used to get the rows and columns with particular condition. It will give the rows where age is 80.

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
630,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,30.0

In [ ]:
data.loc[(data['Sex']=='male') & (data['Age']>40)] # It will give the rows where sex is male and age is greater than

## In this above code we can also check >,<,>=,<=,==,!= conditions. We can also use or condition using | operator.

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
6,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,51.8625
33,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,10.5000
35,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,52.0000
54,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,61.9792
62,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,83.4750
...,...,...,...,...,...,...,...,...
845,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,7.5500
851,0,3,"Svensson, Mr. Johan",male,74.0,0,0,7.7750
857,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,26.5500
860,0,3,"Hansen, Mr. Claus Peter",male,41.0,2,0,14.1083
873,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,9.0000

In [ ]:
## age > 22 , fare > 10 , parch >1
data.loc[(data['Age']>22) & (data['Fare']>10) & (data['Parch']>1) & (data['Sex']=='female')] ## For femaele

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
8,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,11.1333
25,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,31.3875
88,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,263.0000
167,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,27.9000
247,1,2,"Hamalainen, Mrs. William (Anna)",female,24.0,0,2,14.5000
254,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,20.2125
255,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.0,0,2,15.2458
318,1,1,"Wick, Miss. Mary Natalie",female,31.0,0,2,164.8667
341,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,263.0000
394,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0,0,2,16.7000
437,1,2,"Richards, Mrs. Sidney (Emily Hocking)",female,24.0,2,3,18.7500
472,1,2,"West, Mrs. Edwy Arthur (Ada Mary Worth)",female,33.0,1,2,27.7500
498,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,151.5500
506,1,2,"Quick, Mrs. Frederick Charles (Jane Richards)",female,33.0,0,2,26.0000
540,1,1,"Crosby, Miss. Harriet R",female,36.0,0,2,71.0000
567,0,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,21.0750
610,0,3,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",female,39.0,1,5,31.2750
615,1,2,"Herman, Miss. Alice",female,24.0,1,2,65.0000
638,0,3,"Panula, Mrs. Juha (Maria Emilia Ojala)",female,41.0,0,5,39.6875
678,0,3,"Goodwin, Mrs. Frederick (Augusta Tyler)",female,43.0,1,6,46.9000
736,0,3,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,34.3750
754,1,2,"Herman, Mrs. Samuel (Jane Laver)",female,48.0,1,2,65.0000
763,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,120.0000
774,1,2,"Hocking, Mrs. Elizabeth (Eliza Needs)",female,54.0,1,3,23.0000
858,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,19.2583
885,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,29.1250

In [34]:
data.loc[(data['Age']>22) & (data['Fare']>10) & (data['Parch']>1) & (data['Sex']=='male')] ## for male

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
13,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,31.2750
93,0,3,"Dean, Mr. Bertram Frank",male,26.0,1,2,20.5750
148,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,26.0000
153,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,14.5000
360,0,3,"Skoog, Mr. Wilhelm",male,40.0,1,4,27.9000
377,0,1,"Widener, Mr. Harry Elkins",male,27.0,0,2,211.5000
390,1,1,"Carter, Mr. William Ernest",male,36.0,1,2,120.0000
438,0,1,"Fortune, Mr. Mark",male,64.0,1,4,263.0000
450,0,2,"West, Mr. Edwy Arthur",male,36.0,1,2,27.7500
659,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,113.2750
685,0,2,"Laroche, Mr. Joseph Philippe Lemercier",male,25.0,1,2,41.5792

In [37]:
# number of females in first class
data.loc[(data["Sex"]=="female") & (data["Pclass"]==1)]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000
11,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,26.5500
31,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,146.5208
52,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,76.7292
...,...,...,...,...,...,...,...,...
856,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,164.8667
862,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,25.9292
871,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,52.5542
879,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,83.1583
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000

In [39]:
data.iloc[np.where(data['Age']==80)] ## iloc is used to get the rows and columns with particular condition. It will give the rows where age is 80.

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
630,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,30.0

In [40]:
data.iloc[np.where((data['Sex']=='male') & (data['Survived']==1))] ## It will give the rows where sex is male and survived is 1. We can also use or condition using | operator.

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
17,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,13.0000
21,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,13.0000
23,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,35.5000
36,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,7.2292
55,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,35.5000
...,...,...,...,...,...,...,...,...
838,1,3,"Chip, Mr. Chang",male,32.0,0,0,56.4958
839,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,29.7000
857,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,26.5500
869,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,11.1333
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000

In [49]:
data.iloc[np.where((data['Fare']>10) & (data['Age']>50) & (data['Parch']==1) & (data['Sex']=='male'))]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
54,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,61.9792
124,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,77.2875
155,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,61.3792
262,0,1,"Taussig, Mr. Emil",male,52.0,1,1,79.6500
587,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,79.2000
684,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,39.0000
745,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,71.0000

In [50]:
data.iloc[np.where((data['Fare']>10) & (data['Age']>50) & (data['Parch']==1) & (data['Sex']=='female'))]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
268,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,153.4625
820,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,93.5000
879,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,83.1583

In [41]:
data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [51]:
data.Sex.unique()

array(['male', 'female'], dtype=object)

In [52]:
data.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
data.Sex.value_counts() # value_counts() is used to get the count of unique values in a column.

Sex
male      577
female    314
Name: count, dtype: int64

In [54]:
data['Age'].isnull().sum() # isnull() is used to check the null values in a column. It will give the count of null values in a column.

np.int64(177)

In [55]:
data['Age'].isna().sum()

np.int64(177)

In [56]:
data['Age'].notnull().sum()

np.int64(714)

In [ ]:
## gettng the specific column from the dataframe
data['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [60]:
pd.set_option('display.max_rows',None) # Displaying all rows of the dataframe

In [ ]:
data

In [ ]:
data.head(890)

In [62]:
pd.reset_option('display.max_rows',None)

In [64]:
data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500

In [ ]:
## Arranging
data.sort_values('Pclass') ## Default ascending order

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
857,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,26.5500
862,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,25.9292
867,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,50.4958
52,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,76.7292
839,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,29.7000
...,...,...,...,...,...,...,...,...
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500

In [4]:
## Arraning
data.sort_values('Pclass',ascending=False) ## Descending order

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250
885,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,29.1250
...,...,...,...,...,...,...,...,...
853,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,39.4000
23,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,35.5000
27,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,263.0000
30,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,27.7208
31,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,146.5208

In [5]:
data.sort_values(by=['Age','Pclass'])

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare
803,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,8.5167
755,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,14.5000
469,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,19.2583
644,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,19.2583
78,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,29.0000
...,...,...,...,...,...,...,...,...
859,0,3,"Razi, Mr. Raihed",male,NaN,0,0,7.2292
863,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,69.5500
868,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,9.5000
878,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,7.8958
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500

In [6]:
print(data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [10]:
data.drop_duplicates(inplace = True )
data.shape

(891, 8)

## Grouping the Data

In [11]:
data.groupby(data['Pclass']).count()

        Survived  Name  Sex  Age  SibSp  Parch  Fare
Pclass
1            216   216  216  186    216    216   216
2            184   184  184  173    184    184   184
3            491   491  491  355    491    491   491

In [12]:
data.groupby(data['Pclass']).max('Fare')

        Survived   Age  SibSp  Parch      Fare
Pclass
1              1  80.0      3      4  512.3292
2              1  70.0      3      3   73.5000
3              1  74.0      8      6   69.5500

In [13]:
data.groupby(data['Sex']).mean('Fare')

        Survived    Pclass        Age     SibSp     Parch       Fare
Sex
female  0.742038  2.159236  27.915709  0.694268  0.649682  44.479818
male    0.188908  2.389948  30.726645  0.429809  0.235702  25.523893

In [14]:
data.groupby(data['Sex']).median('Fare')

        Survived  Pclass   Age  SibSp  Parch  Fare
Sex
female       1.0     2.0  27.0    0.0    0.0  23.0
male         0.0     3.0  29.0    0.0    0.0  10.5

In [17]:
import pandas as pd

values = [['rohan',455],['elvish',250],['Deepak',494],['soni',400],['radhika',500],['vansh',450],]

## Creating a pandas dataframe
df = pd.DataFrame(values,columns=['Name','Total marks'])


## Applying lambda function to find percentage od 'Total marks' column using df.assign()
df = df.assign(Percentage = lambda x : (x['Total marks']/500 *100))

# displaying the data Frame 
df

      Name  Total marks  Percentage
0    rohan          455        91.0
1   elvish          250        50.0
2   Deepak          494        98.8
3     soni          400        80.0
4  radhika          500       100.0
5    vansh          450        90.0

In [ ]:
import pandas as pd

a = pd.DataFrame({"a":[1,2],"b":{3,4}})  
b = pd.DataFrame({"a":[5,6],"b":{7,8}})

res = a.append(b) ## Since we pass input as dictionary so we can't use append 

print(res)

TypeError: 'set' type is unordered